# sherlog

A Clojure Library to query logs in Cloudwatch and S3

Sherlog provides APIs to
- Query and Cloudwatch Log Streams
- Filter and Fetch logs in S3 using AWS S3-select
- Create Metric Filters on Cloudwatch Logs

* Usage

Add below git coordinates in deps.edn

#+BEGIN_SRC clojure
omnyway-labs/sherlog
{:git/url "git@github.com:omnyway-labs/sherlog.git",
 :sha "f1c370711a5b8949af755c3f9997dcf441ba6175"}
#+END_SRC

** Querying Cloudwatch Logs

Make sure you have the necessary IAM permissions to Query Logs in
Cloudwatch and S3

#+BEGIN_SRC clojure
(require '[sherlog.log :as log])
(log/init! {:auth-type :profile
            :profile   (System/getenv "AWS_PROFILE")
            :region    "us-east-1"})
#+END_SRC
Other AWS auth-types:
#+BEGIN_SRC clojure
{:auth-type :env} ;; uses the AWS SECRET environment variables
or {:auth-type :default}

#+begin_src clojure
(log/search log-group PATTERN DURATION-IN-SECS)
#+end_src

Where PATTERN is a clojure map or a jq-like Pattern supported by
Cloudwatch
Examples:

#+begin_src clojure
(log/search log-group "ERROR" 3000)
(log/search log-group "{ $.id = \"id123\" }" 3000)
;; search takes a map; This does an *and* of the entries in the map
(log/search log-group {:id "id123" :log-type "event"} 3000)

(log/tail log-group)
;; returns a log-seq
#+end_src

** Cloudwatch Metric Filters

To list the filters:
#+begin_src clojure
(log/list-filters log-group)
#+end_src

To create a Metric Filter, you could

#+begin_src clojure
(log/create-filter log-group name pattern namespace initial-value)
;; example:
(log/create-filter :foo "my-metric" {:log-type "error"} "errors" 1)
;; this creates a realtime counter of errors in logs

(log/delete-filter log-group name)
#+end_src

** Metrics from Filters

#+BEGIN_SRC clojure
(require '[sherlog.metric :as metric])
(metric/init! {:auth-type :profile
               :profile   (System/getenv "AWS_PROFILE")
               :region    "us-east-1"})
#+END_SRC

#+begin_src clojure
(metric/find metric-namespace)
(metric/show "AWS/Billing" "EstimatedCharges" :currency "1d")
#+end_src


** Fetch Logs in S3 using S3-select

Sherlog uses s3-select to *grep* logs in S3. Currently supports only
GZIPPed JSON encoded logs.

#+BEGIN_SRC clojure
(require '[sherlog.s3 :as s3])
(s3/init! {:auth-type :profile
           :profile   (System/getenv "AWS_PROFILE")
           :region    "us-east-1"})
#+END_SRC

#+begin_src clojure
(s3/select s3-bucket prefix filters)
returns a lazy-seq of the S3 logs.

;; we can optionally write the results to a file
(s3/select "my-bucket" prefix filters "/tmp/data.json")
#+end_src

Let us say we have some data in a S3 bucket like below:
#+BEGIN_SRC json
{"id":1,"name":"foo.bar","address":"Las Vegas","car":"golf", "context": {"request-id": "Root-1=abc"}}
{"id":2,"name":"Ben Mostafa","address":"Las Vegas","car":"Mustang"}
#+END_SRC

We could use simple maps as filters

#+BEGIN_SRC clojure
(s3/select "my-bucket" "2018/12/10" {:id 1})

;; or for nested data use a dotted notation
(s3/select "my-bucket" "2018/12/10" {:context.request-id "Root-1=abc"})
#+END_SRC

* License - Apache 2.0

Copyright 2018 Omnyway Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

[[http://www.apache.org/licenses/LICENSE-2.0]]

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
