version: 2
jobs:
  release:
    parallelism: 1
    working_directory: ~/sherlog
    docker:
      - image: circleci/clojure:latest
    environment:
      - VERSION_FILE: ../VERSION
      - SERVICE_NAME: sherlog
      - GOROOT: ""
      - GOPATH: "/root/.go"
    steps:
      - checkout
      - run: |
          wget https://github.com/omnypay/rico/releases/download/0.1.4/semver-from-git.tar.bz2
          tar jxvf semver-from-git.tar.bz2
          sudo mv semver-from-git/bin/semver-from-git /usr/local/bin/semver-from-git && chmod +x /usr/local/bin/semver-from-git
          sudo mv semver-from-git/lib/* /usr/local/lib/
          sudo rm -rf semver-from-git.tar.bz2

          wget https://github.com/aktau/github-release/releases/download/v0.7.2/linux-amd64-github-release.tar.bz2
          tar jxvf linux-amd64-github-release.tar.bz2
          sudo mv bin/linux/amd64/github-release /usr/local/bin/github-release
          sudo chmod +x /usr/local/bin/github-release
          sudo rm -f linux-amd64-github-release.tar.bz2
      - run: semver-from-git $VERSION_FILE
workflows:
  version: 2
  build_test_release:
    jobs:
      - release:
          filters:
            branches:
              only: master
